name: Build my Application

on: push

jobs:
  build:
    name: Build the App
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v2
      - name: Print Current Directory 
        run: pwd
      - name: List Files in Directory
        run: ls
      - name: Check DotNet CLi
        run: dotnet build
      - name: List Files in Tricking
        run: ls TrickingLibrary.Api -R 
      - name: Check NPM Cli
        run: npm -v